matrix:
  include:
    - DOCKER_RUBY_VERSION: 2.2
      RUBY_IMAGE_TAG: 2.2-latest

    - DOCKER_RUBY_VERSION: 2.3
      RUBY_IMAGE_TAG: 2.3-latest

build:
  image: abakpress/dind-testing
  privileged: true
  volumes:
    - /home/data/drone/images:/images
    - /home/data/drone/gems:/bundle
  environment:
    - COMPOSE_FILE_EXT=drone
    - RAILS_ENV=test
    - RUBY_IMAGE_TAG=2.2-latest
  commands:
    - wrapdocker docker -v

    - fetch-images
      --image abakpress/ruby-app:$RUBY_IMAGE_TAG

    - dip provision
    - dip rspec

  release:
    image: abakpress/gem-publication
    pull: true
    when:
      event: push
      branch: master
    volumes:
      - /home/data/drone/rubygems:/root/.gem
    commands:
      - release-gem --public
